server:
  port: 8080
spring:
application:
  name: ml-mutants
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME}
    url: ${DATABASE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    # JPA properties
    jpa:
      hibernate:
        ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
      show-sql: true
      database: postgresql
      database-platform: ${SPRING_JPA_DATABASE-PLATFORM}
      open-in-view: false
      generate-ddl: true

# Configuration Logging
  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug

mercado-libre-mutants:
  version: '@project.version@'
  prefix: 'ml-mutants:'
  code:
    ok: '000:000'
    error:
      business: 400
      server: 500