server:
  port: 8080
spring:
application:
  name: ml-mutants
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://zwjnmdjzopqlnp:b26c13128f11a7198e4fc6164a66362b3cb06728a5c258456d29a133ab6d4566@ec2-52-72-99-110.compute-1.amazonaws.com:5432/d16o9idpc74t92
    username: zwjnmdjzopqlnp
    password: b26c13128f11a7198e4fc6164a66362b3cb06728a5c258456d29a133ab6d4566
    # JPA properties
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true

# Configuration Logging
  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug

mercado-libre-mutants:
  version: '@project.version@'
  prefix: 'ml-mutants:'
  code:
    ok: '000:000'
    error:
      business: 400
      server: 500