server:
  port: 8080
spring:
application:
  name: ml-mutants
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
#Swagger API doc
swagger:
  allowed: true
  api:
    title: ml-mutants
    version: '@project.version@'
    description: mutants api.

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

# Configuration Logging
logging:
  level:
    root: INFO

mercado-libre-mutants:
  version: '@project.version@'
  prefix: 'ml-mutants:'
  code:
    ok: '000:000'
    error:
      business: 400
      server: 500