server:
  port: 8080
spring:
application:
  name: ml-mutants
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Dna
    username: postgres
    password:
    # JPA properties
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true
#Swagger API doc
swagger:
  allowed: true
  api:
    title: ml-mutants
    version: '@project.version@'
    description: mutants api.

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

# Configuration Logging
  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug

mercado-libre-mutants:
  version: '@project.version@'
  prefix: 'ml-mutants:'
  code:
    ok: '000:000'
    error:
      business: 400
      server: 500